version: '3'

services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - 21:21
      - 21000-21010:21000-21010
    environment:
      USERS: 'hikvision|jumper|/home/user'
      ADDRESS: 'localhost'
    volumes:
      - './ftp-contents:/home/user:ro'
