version: '3'

services:
  # https://hub.docker.com/_/wordpress
  wordpress:
    build: .
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PWD}
    volumes:
      - "wp:/var/www/html:rw"
      - "./wp-content:/var/www/html/wp-content:rw"

  mysql:
    image: "mysql:5.7"
    ports:
      - "31340:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PWD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      # MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PWD}
    volumes:
      - db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  wp-cli:
    image: "wordpress:cli-php7.1"
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PWD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_PORT: ${WORDPRESS_PORT}
      WORDPRESS_IP: ${WORDPRESS_IP}
      WORDPRESS_ADMIN_LOGIN: ${WORDPRESS_ADMIN_LOGIN}
      WORDPRESS_ADMIN_PWD: ${WORDPRESS_ADMIN_PWD}
    depends_on:
      - "mysql"
      - "wordpress"
    volumes:
      - "wp:/var/www/html:rw"
      - "./wp-content:/var/www/html/wp-content:rw"
      - "./install-wp.sh:/usr/local/bin/install-wp:ro"
      - "./dump.sql:/sql-dump/dump.sql:ro"

volumes:
  db: {}
  wp: {}
