extends:
  file: common.yml
  service: webapp

services:
  web:
    image: alpine:latest
    init: true
    command: bundle exec thin -p 3000
    entrypoint: /code/entrypoint.sh
    labels:
      com.example.department: "IT"
    volumes_from: nginx

  backend:
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /var/run/postgres/postgres.sock
        target: /var/run/postgres/postgres.sock
