version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - "db:/data/db"
      - ./mongo-seed/data:/database/mongo-seed
      - ./mongo-seed/import.sh:/docker-entrypoint-initdb.d/import.sh
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME:
    #   MONGO_INITDB_ROOT_PASSWORD:

  mongo-client:
    container_name: mongo-client
    image: mongoclient/mongoclient
    restart: always
    ports:
      - '27018:3000'


volumes:
  db: {}
