services:
  proxy:
    build: ./proxy
    networks:
      - frontend

  app:
    build: ./app
    networks:
      - frontend
      - backend

  db:
    image: postgres
    networks:
      - backend


networks:
  frontend:
  backend:
    external: true
    name: backend
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"
